server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /money-manager/ {
        try_files $uri $uri/ /money-manager/index.html;
    }

    location /api/ {
        proxy_pass http://money-manager-backend:3001;
        proxy_set_header Host $host;
    }
}
