FROM node:20-alpine AS builder
WORKDIR /app
COPY backend/package.json ./
RUN yarn install
COPY backend/ .
RUN yarn build

FROM node:20-alpine
WORKDIR /app
COPY backend/package.json ./
RUN yarn install --production
COPY --from=builder /app/dist ./dist
CMD ["yarn", "start"]
